export type Category =
  | "cpu"
  | "gpu"
  | "motherboard"
  | "ram"
  | "storage"
  | "psu"
  | "cooler"
  | "case";

export const CATEGORIES: { id: Category; label: string; labelAr: string }[] = [
  { id: "cpu", label: "Processor", labelAr: "المعالج" },
  { id: "gpu", label: "Graphics Card", labelAr: "بطاقة الرسومات" },
  { id: "motherboard", label: "Motherboard", labelAr: "اللوحة الأم" },
  { id: "ram", label: "Memory", labelAr: "الذاكرة العشوائية" },
  { id: "storage", label: "Storage", labelAr: "التخزين" },
  { id: "psu", label: "Power Supply", labelAr: "مزوّد الطاقة" },
  { id: "cooler", label: "CPU Cooler", labelAr: "مبرّد المعالج" },
  { id: "case", label: "Case", labelAr: "الصندوق" },
];


export type Socket =
  | "AM5"
  | "AM4"
  | "LGA1700"
  | "LGA1851"
  | "LGA1151"
  | "LGA1151v2"
  | "LGA1200";
export type MemoryType = "DDR4" | "DDR5";
export type FormFactor = "ATX" | "Micro-ATX" | "Mini-ITX";

export interface BasePart {
  id: string;
  name: string;
  brand: string;
  category: Category;
  price: number;
  rating: number;
  tdp: number;
  specs: string[];
}

export interface CpuPart extends BasePart {
  category: "cpu";
  socket: Socket;
  memoryType: MemoryType[];
  cores: number;
  /** relative gaming CPU power, 100 = 5800X3D class */
  cpuScore: number;
  integratedGraphics: boolean;
  coolerIncluded: boolean;
}

export interface GpuPart extends BasePart {
  category: "gpu";
  vram: number;
  lengthMm: number;
  /** relative raster power, 100 = RTX 4070 class */
  gpuScore: number;
  rayTracing: boolean;
  upscaler: "DLSS" | "FSR" | "XeSS";
}

export interface MotherboardPart extends BasePart {
  category: "motherboard";
  socket: Socket;
  memoryType: MemoryType;
  formFactor: FormFactor;
  memorySlots: number;
  maxMemory: number;
}

export interface RamPart extends BasePart {
  category: "ram";
  memoryType: MemoryType;
  capacity: number;
  modules: number;
  speed: number;
}

export interface StoragePart extends BasePart {
  category: "storage";
  capacity: number;
  kind: "NVMe SSD" | "SATA SSD" | "HDD";
}

export interface PsuPart extends BasePart {
  category: "psu";
  wattage: number;
  efficiency: string;
  modular: string;
}

export interface CoolerPart extends BasePart {
  category: "cooler";
  sockets: Socket[];
  heightMm: number;
  coolingCapacity: number;
  kind: "Air" | "AIO Liquid";
}

export interface CasePart extends BasePart {
  category: "case";
  supportedFormFactors: FormFactor[];
  maxGpuLengthMm: number;
  maxCoolerHeightMm: number;
}

export type Part =
  | CpuPart
  | GpuPart
  | MotherboardPart
  | RamPart
  | StoragePart
  | PsuPart
  | CoolerPart
  | CasePart;

const cpus: CpuPart[] = [
  {
    id: "cpu-7800x3d",
    name: "Ryzen 7 7800X3D",
    brand: "AMD",
    category: "cpu",
    price: 91000,
    rating: 4.9,
    tdp: 120,
    socket: "AM5",
    memoryType: ["DDR5"],
    cores: 8,
    cpuScore: 152,
    integratedGraphics: true,
    coolerIncluded: false,
    specs: ["8C/16T", "5.0 GHz Boost", "96MB 3D V-Cache"],
  },
  {
    id: "cpu-9800x3d",
    name: "Ryzen 7 9800X3D",
    brand: "AMD",
    category: "cpu",
    price: 117000,
    rating: 4.9,
    tdp: 120,
    socket: "AM5",
    memoryType: ["DDR5"],
    cores: 8,
    cpuScore: 175,
    integratedGraphics: true,
    coolerIncluded: false,
    specs: ["8C/16T", "5.2 GHz Boost", "Zen 5 3D V-Cache"],
  },
  {
    id: "cpu-7600",
    name: "Ryzen 5 7600",
    brand: "AMD",
    category: "cpu",
    price: 41500,
    rating: 4.7,
    tdp: 65,
    socket: "AM5",
    memoryType: ["DDR5"],
    cores: 6,
    cpuScore: 118,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["6C/12T", "5.1 GHz Boost", "Wraith Stealth included"],
  },
  {
    id: "cpu-5600",
    name: "Ryzen 5 5600",
    brand: "AMD",
    category: "cpu",
    price: 23500,
    rating: 4.6,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 92,
    integratedGraphics: false,
    coolerIncluded: true,
    specs: ["6C/12T", "4.4 GHz Boost", "Budget king"],
  },
  {
    id: "cpu-14600k",
    name: "Core i5-14600K",
    brand: "Intel",
    category: "cpu",
    price: 69900,
    rating: 4.6,
    tdp: 181,
    socket: "LGA1700",
    memoryType: ["DDR4", "DDR5"],
    cores: 14,
    cpuScore: 128,
    integratedGraphics: true,
    coolerIncluded: false,
    specs: ["14C/20T", "5.3 GHz Boost", "Unlocked"],
  },
  {
    id: "cpu-14900k",
    name: "Core i9-14900K",
    brand: "Intel",
    category: "cpu",
    price: 130000,
    rating: 4.5,
    tdp: 253,
    socket: "LGA1700",
    memoryType: ["DDR4", "DDR5"],
    cores: 24,
    cpuScore: 160,
    integratedGraphics: true,
    coolerIncluded: false,
    specs: ["24C/32T", "6.0 GHz Boost", "Needs strong cooling"],
  },
  {
    id: "cpu-265k",
    name: "Core Ultra 7 265K",
    brand: "Intel",
    category: "cpu",
    price: 85000,
    rating: 4.3,
    tdp: 250,
    socket: "LGA1851",
    memoryType: ["DDR5"],
    cores: 20,
    cpuScore: 145,
    integratedGraphics: true,
    coolerIncluded: false,
    specs: ["20C/20T", "5.5 GHz Boost", "Arrow Lake"],
  },
  // ===== Ryzen G APUs (integrated graphics) — very common in Algeria =====
  {
    id: "cpu-3400g",
    name: "Ryzen 5 3400G",
    brand: "AMD",
    category: "cpu",
    price: 14500,
    rating: 4.2,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 4,
    cpuScore: 58,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["4C/8T", "4.2 GHz Boost", "Vega 11 graphics"],
  },
  {
    id: "cpu-4600g",
    name: "Ryzen 5 4600G",
    brand: "AMD",
    category: "cpu",
    price: 19800,
    rating: 4.6,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 85,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["6C/12T", "4.2 GHz Boost", "Vega 7 graphics"],
  },
  {
    id: "cpu-5500g",
    name: "Ryzen 5 5500G",
    brand: "AMD",
    category: "cpu",
    price: 22500,
    rating: 4.5,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 90,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["6C/12T", "4.4 GHz Boost", "Vega 7 graphics"],
  },
  {
    id: "cpu-5600g",
    name: "Ryzen 5 5600G",
    brand: "AMD",
    category: "cpu",
    price: 26500,
    rating: 4.8,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 92,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["6C/12T", "4.4 GHz Boost", "Vega 7 graphics"],
  },
  {
    id: "cpu-5650g",
    name: "Ryzen 5 PRO 5650G",
    brand: "AMD",
    category: "cpu",
    price: 29000,
    rating: 4.6,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 94,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["6C/12T", "4.4 GHz Boost", "Vega 7 graphics"],
  },
  {
    id: "cpu-5700g",
    name: "Ryzen 7 5700G",
    brand: "AMD",
    category: "cpu",
    price: 36500,
    rating: 4.7,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 8,
    cpuScore: 105,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["8C/16T", "4.6 GHz Boost", "Vega 8 graphics"],
  },
  {
    id: "cpu-8500g",
    name: "Ryzen 5 8500G",
    brand: "AMD",
    category: "cpu",
    price: 38500,
    rating: 4.4,
    tdp: 65,
    socket: "AM5",
    memoryType: ["DDR5"],
    cores: 6,
    cpuScore: 105,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["6C/12T", "5.0 GHz Boost", "Radeon 740M graphics"],
  },
  {
    id: "cpu-8600g",
    name: "Ryzen 5 8600G",
    brand: "AMD",
    category: "cpu",
    price: 48000,
    rating: 4.6,
    tdp: 65,
    socket: "AM5",
    memoryType: ["DDR5"],
    cores: 6,
    cpuScore: 118,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["6C/12T", "5.0 GHz Boost", "Radeon 760M graphics"],
  },
  {
    id: "cpu-8700g",
    name: "Ryzen 7 8700G",
    brand: "AMD",
    category: "cpu",
    price: 66000,
    rating: 4.7,
    tdp: 65,
    socket: "AM5",
    memoryType: ["DDR5"],
    cores: 8,
    cpuScore: 132,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["8C/16T", "5.1 GHz Boost", "Radeon 780M graphics"],
  },
];

const gpus: GpuPart[] = [
  {
    id: "gpu-4060",
    name: "GeForce RTX 4060 8GB",
    brand: "NVIDIA",
    category: "gpu",
    price: 98000,
    rating: 4.2,
    tdp: 115,
    vram: 8,
    lengthMm: 245,
    gpuScore: 62,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["8GB GDDR6", "DLSS 3", "1080p champion"],
  },
  {
    id: "gpu-4070s",
    name: "GeForce RTX 4070 SUPER",
    brand: "NVIDIA",
    category: "gpu",
    price: 172000,
    rating: 4.8,
    tdp: 220,
    vram: 12,
    lengthMm: 305,
    gpuScore: 118,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["12GB GDDR6X", "DLSS 3", "1440p high refresh"],
  },
  {
    id: "gpu-4080s",
    name: "GeForce RTX 4080 SUPER",
    brand: "NVIDIA",
    category: "gpu",
    price: 315000,
    rating: 4.8,
    tdp: 320,
    vram: 16,
    lengthMm: 336,
    gpuScore: 165,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["16GB GDDR6X", "DLSS 3", "4K ready"],
  },
  {
    id: "gpu-5090",
    name: "GeForce RTX 5090",
    brand: "NVIDIA",
    category: "gpu",
    price: 1240000,
    rating: 4.9,
    tdp: 575,
    vram: 32,
    lengthMm: 304,
    gpuScore: 275,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["32GB GDDR7", "DLSS 4", "No compromise 4K"],
  },
  {
    id: "gpu-7800xt",
    name: "Radeon RX 7800 XT",
    brand: "AMD",
    category: "gpu",
    price: 155000,
    rating: 4.6,
    tdp: 263,
    vram: 16,
    lengthMm: 267,
    gpuScore: 112,
    rayTracing: true,
    upscaler: "FSR",
    specs: ["16GB GDDR6", "FSR 3", "Great value 1440p"],
  },
  {
    id: "gpu-9070xt",
    name: "Radeon RX 9070 XT",
    brand: "AMD",
    category: "gpu",
    price: 259000,
    rating: 4.7,
    tdp: 304,
    vram: 16,
    lengthMm: 320,
    gpuScore: 155,
    rayTracing: true,
    upscaler: "FSR",
    specs: ["16GB GDDR6", "FSR 4", "RDNA 4"],
  },
  {
    id: "gpu-b580",
    name: "Arc B580 12GB",
    brand: "Intel",
    category: "gpu",
    price: 95000,
    rating: 4.4,
    tdp: 190,
    vram: 12,
    lengthMm: 272,
    gpuScore: 68,
    rayTracing: true,
    upscaler: "XeSS",
    specs: ["12GB GDDR6", "XeSS 2", "Budget 1440p"],
  },
  {
    id: "gpu-5060",
    name: "GeForce RTX 5060 8GB",
    brand: "NVIDIA",
    category: "gpu",
    price: 98000,
    rating: 4.3,
    tdp: 145,
    vram: 8,
    lengthMm: 250,
    gpuScore: 74,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["8GB GDDR7", "DLSS 4", "1080p high refresh"],
  },
  {
    id: "gpu-5060ti16",
    name: "GeForce RTX 5060 Ti 16GB",
    brand: "NVIDIA",
    category: "gpu",
    price: 155000,
    rating: 4.5,
    tdp: 180,
    vram: 16,
    lengthMm: 280,
    gpuScore: 96,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["16GB GDDR7", "DLSS 4", "1440p"],
  },
  {
    id: "gpu-5070",
    name: "GeForce RTX 5070 12GB",
    brand: "NVIDIA",
    category: "gpu",
    price: 190000,
    rating: 4.6,
    tdp: 250,
    vram: 12,
    lengthMm: 300,
    gpuScore: 126,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["12GB GDDR7", "DLSS 4", "1440p ultra"],
  },
  {
    id: "gpu-5070ti",
    name: "GeForce RTX 5070 Ti 16GB",
    brand: "NVIDIA",
    category: "gpu",
    price: 285000,
    rating: 4.7,
    tdp: 300,
    vram: 16,
    lengthMm: 304,
    gpuScore: 165,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["16GB GDDR7", "DLSS 4", "1440p/4K"],
  },
  {
    id: "gpu-5080",
    name: "GeForce RTX 5080 16GB",
    brand: "NVIDIA",
    category: "gpu",
    price: 379000,
    rating: 4.7,
    tdp: 360,
    vram: 16,
    lengthMm: 330,
    gpuScore: 200,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["16GB GDDR7", "DLSS 4", "4K gaming"],
  },
  {
    id: "gpu-9060xt",
    name: "Radeon RX 9060 XT 16GB",
    brand: "AMD",
    category: "gpu",
    price: 168000,
    rating: 4.5,
    tdp: 182,
    vram: 16,
    lengthMm: 290,
    gpuScore: 92,
    rayTracing: true,
    upscaler: "FSR",
    specs: ["16GB GDDR6", "FSR 4", "1440p value"],
  },
  {
    id: "gpu-7600",
    name: "Radeon RX 7600 8GB",
    brand: "AMD",
    category: "gpu",
    price: 85000,
    rating: 4.2,
    tdp: 165,
    vram: 8,
    lengthMm: 240,
    gpuScore: 60,
    rayTracing: true,
    upscaler: "FSR",
    specs: ["8GB GDDR6", "FSR 3", "1080p"],
  },
  {
    id: "gpu-3050",
    name: "GeForce RTX 3050 8GB",
    brand: "NVIDIA",
    category: "gpu",
    price: 75000,
    rating: 3.9,
    tdp: 130,
    vram: 8,
    lengthMm: 230,
    gpuScore: 40,
    rayTracing: true,
    upscaler: "DLSS",
    specs: ["8GB GDDR6", "DLSS 3", "1080p entry"],
  },
  // ===== Radeon RX classics — widely available new/renewed in Algeria =====
  {
    id: "gpu-rx550",
    name: "Radeon RX 550 4GB",
    brand: "AMD",
    category: "gpu",
    price: 12500,
    rating: 3.6,
    tdp: 50,
    vram: 4,
    lengthMm: 170,
    gpuScore: 12,
    rayTracing: false,
    upscaler: "FSR",
    specs: ["4GB GDDR5", "Low power 50W", "Esports / office"],
  },
  {
    id: "gpu-rx570",
    name: "Radeon RX 570 8GB",
    brand: "AMD",
    category: "gpu",
    price: 22000,
    rating: 4.1,
    tdp: 150,
    vram: 8,
    lengthMm: 240,
    gpuScore: 28,
    rayTracing: false,
    upscaler: "FSR",
    specs: ["8GB GDDR5", "1080p medium", "Polaris classic"],
  },
  {
    id: "gpu-rx580",
    name: "Radeon RX 580 8GB",
    brand: "AMD",
    category: "gpu",
    price: 26000,
    rating: 4.2,
    tdp: 185,
    vram: 8,
    lengthMm: 245,
    gpuScore: 34,
    rayTracing: false,
    upscaler: "FSR",
    specs: ["8GB GDDR5", "1080p high", "Most popular budget card"],
  },
  {
    id: "gpu-rx5500xt",
    name: "Radeon RX 5500 XT 8GB",
    brand: "AMD",
    category: "gpu",
    price: 38000,
    rating: 4.0,
    tdp: 130,
    vram: 8,
    lengthMm: 235,
    gpuScore: 38,
    rayTracing: false,
    upscaler: "FSR",
    specs: ["8GB GDDR6", "FSR 3", "1080p"],
  },
  {
    id: "gpu-rx6500xt",
    name: "Radeon RX 6500 XT 4GB",
    brand: "AMD",
    category: "gpu",
    price: 42000,
    rating: 3.8,
    tdp: 107,
    vram: 4,
    lengthMm: 240,
    gpuScore: 36,
    rayTracing: true,
    upscaler: "FSR",
    specs: ["4GB GDDR6", "FSR 3", "1080p esports"],
  },
  {
    id: "gpu-rx6600",
    name: "Radeon RX 6600 8GB",
    brand: "AMD",
    category: "gpu",
    price: 62000,
    rating: 4.5,
    tdp: 132,
    vram: 8,
    lengthMm: 240,
    gpuScore: 55,
    rayTracing: true,
    upscaler: "FSR",
    specs: ["8GB GDDR6", "FSR 3", "Best 1080p value"],
  },
  {
    id: "gpu-rx6650xt",
    name: "Radeon RX 6650 XT 8GB",
    brand: "AMD",
    category: "gpu",
    price: 72000,
    rating: 4.4,
    tdp: 176,
    vram: 8,
    lengthMm: 250,
    gpuScore: 62,
    rayTracing: true,
    upscaler: "FSR",
    specs: ["8GB GDDR6", "FSR 3", "1080p ultra"],
  },
  {
    id: "gpu-rx6700xt",
    name: "Radeon RX 6700 XT 12GB",
    brand: "AMD",
    category: "gpu",
    price: 98000,
    rating: 4.6,
    tdp: 230,
    vram: 12,
    lengthMm: 267,
    gpuScore: 85,
    rayTracing: true,
    upscaler: "FSR",
    specs: ["12GB GDDR6", "FSR 3", "1440p value"],
  },
];

const motherboards: MotherboardPart[] = [
  {
    id: "mb-b650",
    name: "TUF Gaming B650-PLUS",
    brand: "ASUS",
    category: "motherboard",
    price: 49000,
    rating: 4.6,
    tdp: 30,
    socket: "AM5",
    memoryType: "DDR5",
    formFactor: "ATX",
    memorySlots: 4,
    maxMemory: 192,
    specs: ["AM5", "DDR5", "ATX", "PCIe 4.0"],
  },
  {
    id: "mb-x670e",
    name: "ROG Strix X670E-E",
    brand: "ASUS",
    category: "motherboard",
    price: 95000,
    rating: 4.7,
    tdp: 40,
    socket: "AM5",
    memoryType: "DDR5",
    formFactor: "ATX",
    memorySlots: 4,
    maxMemory: 192,
    specs: ["AM5", "DDR5", "ATX", "PCIe 5.0"],
  },
  {
    id: "mb-b650i",
    name: "B650I AORUS Ultra",
    brand: "Gigabyte",
    category: "motherboard",
    price: 62000,
    rating: 4.5,
    tdp: 25,
    socket: "AM5",
    memoryType: "DDR5",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    maxMemory: 96,
    specs: ["AM5", "DDR5", "Mini-ITX", "Wi-Fi 6E"],
  },
  {
    id: "mb-b550",
    name: "MAG B550 TOMAHAWK",
    brand: "MSI",
    category: "motherboard",
    price: 32000,
    rating: 4.7,
    tdp: 25,
    socket: "AM4",
    memoryType: "DDR4",
    formFactor: "ATX",
    memorySlots: 4,
    maxMemory: 128,
    specs: ["AM4", "DDR4", "ATX", "PCIe 4.0"],
  },
  {
    id: "mb-z790",
    name: "Z790 AORUS Elite AX",
    brand: "Gigabyte",
    category: "motherboard",
    price: 83500,
    rating: 4.6,
    tdp: 35,
    socket: "LGA1700",
    memoryType: "DDR5",
    formFactor: "ATX",
    memorySlots: 4,
    maxMemory: 192,
    specs: ["LGA1700", "DDR5", "ATX", "Wi-Fi 6E"],
  },
  {
    id: "mb-b760m",
    name: "PRO B760M-A DDR4",
    brand: "MSI",
    category: "motherboard",
    price: 34000,
    rating: 4.4,
    tdp: 25,
    socket: "LGA1700",
    memoryType: "DDR4",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    maxMemory: 128,
    specs: ["LGA1700", "DDR4", "Micro-ATX"],
  },
  {
    id: "mb-z890",
    name: "Z890 Carbon WiFi",
    brand: "MSI",
    category: "motherboard",
    price: 98000,
    rating: 4.5,
    tdp: 40,
    socket: "LGA1851",
    memoryType: "DDR5",
    formFactor: "ATX",
    memorySlots: 4,
    maxMemory: 256,
    specs: ["LGA1851", "DDR5", "ATX", "PCIe 5.0"],
  },
];

const rams: RamPart[] = [
  {
    id: "ram-ddr5-32-6000",
    name: "Vengeance 32GB (2x16) DDR5-6000",
    brand: "Corsair",
    category: "ram",
    price: 40000,
    rating: 4.8,
    tdp: 10,
    memoryType: "DDR5",
    capacity: 32,
    modules: 2,
    speed: 6000,
    specs: ["DDR5-6000 CL30", "2x16GB", "EXPO/XMP"],
  },
  {
    id: "ram-ddr5-16-5600",
    name: "Fury Beast 16GB (2x8) DDR5-5600",
    brand: "Kingston",
    category: "ram",
    price: 28000,
    rating: 4.5,
    tdp: 8,
    memoryType: "DDR5",
    capacity: 16,
    modules: 2,
    speed: 5600,
    specs: ["DDR5-5600 CL36", "2x8GB"],
  },
  {
    id: "ram-ddr5-64-6400",
    name: "Trident Z5 64GB (2x32) DDR5-6400",
    brand: "G.Skill",
    category: "ram",
    price: 72000,
    rating: 4.7,
    tdp: 12,
    memoryType: "DDR5",
    capacity: 64,
    modules: 2,
    speed: 6400,
    specs: ["DDR5-6400 CL32", "2x32GB", "RGB"],
  },
  {
    id: "ram-ddr4-32-3600",
    name: "Ripjaws V 32GB (2x16) DDR4-3600",
    brand: "G.Skill",
    category: "ram",
    price: 27500,
    rating: 4.7,
    tdp: 10,
    memoryType: "DDR4",
    capacity: 32,
    modules: 2,
    speed: 3600,
    specs: ["DDR4-3600 CL16", "2x16GB"],
  },
  {
    id: "ram-ddr4-16-3200",
    name: "Vengeance LPX 16GB (2x8) DDR4-3200",
    brand: "Corsair",
    category: "ram",
    price: 16000,
    rating: 4.6,
    tdp: 8,
    memoryType: "DDR4",
    capacity: 16,
    modules: 2,
    speed: 3200,
    specs: ["DDR4-3200 CL16", "2x8GB"],
  },
];

const storages: StoragePart[] = [
  {
    id: "ssd-990-1tb",
    name: "990 PRO 1TB NVMe",
    brand: "Samsung",
    category: "storage",
    price: 32000,
    rating: 4.9,
    tdp: 8,
    capacity: 1000,
    kind: "NVMe SSD",
    specs: ["7450 MB/s read", "PCIe 4.0", "1TB"],
  },
  {
    id: "ssd-sn850-2tb",
    name: "WD Black SN850X 2TB",
    brand: "Western Digital",
    category: "storage",
    price: 59000,
    rating: 4.8,
    tdp: 9,
    capacity: 2000,
    kind: "NVMe SSD",
    specs: ["7300 MB/s read", "PCIe 4.0", "2TB"],
  },
  {
    id: "ssd-mx500-1tb",
    name: "MX500 1TB SATA",
    brand: "Crucial",
    category: "storage",
    price: 16000,
    rating: 4.6,
    tdp: 5,
    capacity: 1000,
    kind: "SATA SSD",
    specs: ["560 MB/s read", "2.5 inch", "1TB"],
  },
  {
    id: "hdd-barracuda-4tb",
    name: "BarraCuda 4TB HDD",
    brand: "Seagate",
    category: "storage",
    price: 24000,
    rating: 4.3,
    tdp: 10,
    capacity: 4000,
    kind: "HDD",
    specs: ["5400 RPM", "Mass storage", "4TB"],
  },
];

const psus: PsuPart[] = [
  {
    id: "psu-550",
    name: "CX550M 550W",
    brand: "Corsair",
    category: "psu",
    price: 15000,
    rating: 4.4,
    tdp: 0,
    wattage: 550,
    efficiency: "80+ Bronze",
    modular: "Semi-modular",
    specs: ["550W", "80+ Bronze"],
  },
  {
    id: "psu-750",
    name: "RM750e 750W",
    brand: "Corsair",
    category: "psu",
    price: 24000,
    rating: 4.7,
    tdp: 0,
    wattage: 750,
    efficiency: "80+ Gold",
    modular: "Fully modular",
    specs: ["750W", "80+ Gold", "ATX 3.0"],
  },
  {
    id: "psu-850",
    name: "SuperNOVA 850 G7",
    brand: "EVGA",
    category: "psu",
    price: 36000,
    rating: 4.6,
    tdp: 0,
    wattage: 850,
    efficiency: "80+ Gold",
    modular: "Fully modular",
    specs: ["850W", "80+ Gold"],
  },
  {
    id: "psu-1200",
    name: "Toughpower GF3 1200W",
    brand: "Thermaltake",
    category: "psu",
    price: 72000,
    rating: 4.7,
    tdp: 0,
    wattage: 1200,
    efficiency: "80+ Platinum",
    modular: "Fully modular",
    specs: ["1200W", "80+ Platinum", "12VHPWR"],
  },
];

const coolers: CoolerPart[] = [
  {
    id: "cool-ak620",
    name: "AK620 Dual Tower",
    brand: "DeepCool",
    category: "cooler",
    price: 14000,
    rating: 4.8,
    tdp: 6,
    sockets: ["AM5", "AM4", "LGA1700", "LGA1851", "LGA1151", "LGA1151v2", "LGA1200"],
    heightMm: 160,
    coolingCapacity: 260,
    kind: "Air",
    specs: ["Dual tower air", "160mm tall"],
  },
  {
    id: "cool-pa120",
    name: "Peerless Assassin 120 SE",
    brand: "Thermalright",
    category: "cooler",
    price: 8500,
    rating: 4.9,
    tdp: 5,
    sockets: ["AM5", "AM4", "LGA1700", "LGA1151", "LGA1151v2", "LGA1200"],
    heightMm: 155,
    coolingCapacity: 245,
    kind: "Air",
    specs: ["Best value air", "155mm tall"],
  },
  {
    id: "cool-l12s",
    name: "Noctua NH-L12S",
    brand: "Noctua",
    category: "cooler",
    price: 15000,
    rating: 4.7,
    tdp: 4,
    sockets: ["AM5", "AM4", "LGA1700", "LGA1151", "LGA1151v2", "LGA1200"],
    heightMm: 70,
    coolingCapacity: 120,
    kind: "Air",
    specs: ["Low profile", "70mm tall"],
  },
  {
    id: "cool-aio360",
    name: "Kraken 360 AIO",
    brand: "NZXT",
    category: "cooler",
    price: 45000,
    rating: 4.6,
    tdp: 12,
    sockets: ["AM5", "AM4", "LGA1700", "LGA1851", "LGA1151", "LGA1151v2", "LGA1200"],
    heightMm: 55,
    coolingCapacity: 320,
    kind: "AIO Liquid",
    specs: ["360mm radiator", "LCD display"],
  },
];

const cases: CasePart[] = [
  {
    id: "case-lancool",
    name: "Lancool 216 ATX",
    brand: "Lian Li",
    category: "case",
    price: 26000,
    rating: 4.8,
    tdp: 0,
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 392,
    maxCoolerHeightMm: 180,
    specs: ["Mid tower", "High airflow", "392mm GPU"],
  },
  {
    id: "case-h5flow",
    name: "H5 Flow",
    brand: "NZXT",
    category: "case",
    price: 22000,
    rating: 4.5,
    tdp: 0,
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 365,
    maxCoolerHeightMm: 165,
    specs: ["Mid tower", "Tempered glass"],
  },
  {
    id: "case-a4h2o",
    name: "A4-H2O Mini-ITX",
    brand: "Lian Li",
    category: "case",
    price: 32000,
    rating: 4.4,
    tdp: 0,
    supportedFormFactors: ["Mini-ITX"],
    maxGpuLengthMm: 322,
    maxCoolerHeightMm: 70,
    specs: ["11L SFF", "Vertical GPU"],
  },
  {
    id: "case-4000d",
    name: "4000D Airflow",
    brand: "Corsair",
    category: "case",
    price: 24000,
    rating: 4.8,
    tdp: 0,
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 360,
    maxCoolerHeightMm: 170,
    specs: ["Mid tower", "Airflow front panel"],
  },
];


/** Legacy platforms still very common on the Algerian market (new + used). */
const legacyCpus: CpuPart[] = [
  {
    id: "cpu-3600",
    name: "Ryzen 5 3600",
    brand: "AMD",
    category: "cpu",
    price: 21500,
    rating: 4.7,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 74,
    integratedGraphics: false,
    coolerIncluded: true,
    specs: ["6C/12T", "4.2 GHz Boost", "Zen 2"],
  },
  {
    id: "cpu-3700x",
    name: "Ryzen 7 3700X",
    brand: "AMD",
    category: "cpu",
    price: 28000,
    rating: 4.7,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 8,
    cpuScore: 82,
    integratedGraphics: false,
    coolerIncluded: true,
    specs: ["8C/16T", "4.4 GHz Boost", "Zen 2"],
  },
  {
    id: "cpu-4600g",
    name: "Ryzen 5 4600G",
    brand: "AMD",
    category: "cpu",
    price: 24000,
    rating: 4.5,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 70,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["6C/12T", "Vega 7 iGPU", "Zen 2 APU"],
  },
  {
    id: "cpu-5500",
    name: "Ryzen 5 5500",
    brand: "AMD",
    category: "cpu",
    price: 19000,
    rating: 4.4,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 84,
    integratedGraphics: false,
    coolerIncluded: true,
    specs: ["6C/12T", "4.2 GHz Boost", "Zen 3"],
  },
  {
    id: "cpu-5700x",
    name: "Ryzen 7 5700X",
    brand: "AMD",
    category: "cpu",
    price: 31000,
    rating: 4.8,
    tdp: 65,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 8,
    cpuScore: 104,
    integratedGraphics: false,
    coolerIncluded: false,
    specs: ["8C/16T", "4.6 GHz Boost", "Zen 3"],
  },
  {
    id: "cpu-5800x3d",
    name: "Ryzen 7 5800X3D",
    brand: "AMD",
    category: "cpu",
    price: 55000,
    rating: 4.8,
    tdp: 105,
    socket: "AM4",
    memoryType: ["DDR4"],
    cores: 8,
    cpuScore: 122,
    integratedGraphics: false,
    coolerIncluded: false,
    specs: ["8C/16T", "96MB 3D V-Cache", "Zen 3"],
  },
  {
    id: "cpu-6500",
    name: "Core i5-6500",
    brand: "Intel",
    category: "cpu",
    price: 7000,
    rating: 3.9,
    tdp: 65,
    socket: "LGA1151",
    memoryType: ["DDR4"],
    cores: 4,
    cpuScore: 34,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["4C/4T", "3.6 GHz", "Skylake (6th gen)"],
  },
  {
    id: "cpu-7700",
    name: "Core i7-7700",
    brand: "Intel",
    category: "cpu",
    price: 12000,
    rating: 4.1,
    tdp: 65,
    socket: "LGA1151",
    memoryType: ["DDR4"],
    cores: 4,
    cpuScore: 46,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["4C/8T", "4.2 GHz Boost", "Kaby Lake (7th gen)"],
  },
  {
    id: "cpu-8400",
    name: "Core i5-8400",
    brand: "Intel",
    category: "cpu",
    price: 14000,
    rating: 4.3,
    tdp: 65,
    socket: "LGA1151v2",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 52,
    integratedGraphics: true,
    coolerIncluded: true,
    specs: ["6C/6T", "4.0 GHz Boost", "Coffee Lake (8th gen)"],
  },
  {
    id: "cpu-9400f",
    name: "Core i5-9400F",
    brand: "Intel",
    category: "cpu",
    price: 16000,
    rating: 4.4,
    tdp: 65,
    socket: "LGA1151v2",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 56,
    integratedGraphics: false,
    coolerIncluded: true,
    specs: ["6C/6T", "4.1 GHz Boost", "9th gen"],
  },
  {
    id: "cpu-10400f",
    name: "Core i5-10400F",
    brand: "Intel",
    category: "cpu",
    price: 19500,
    rating: 4.5,
    tdp: 65,
    socket: "LGA1200",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 66,
    integratedGraphics: false,
    coolerIncluded: true,
    specs: ["6C/12T", "4.3 GHz Boost", "10th gen"],
  },
  {
    id: "cpu-11400f",
    name: "Core i5-11400F",
    brand: "Intel",
    category: "cpu",
    price: 22500,
    rating: 4.5,
    tdp: 65,
    socket: "LGA1200",
    memoryType: ["DDR4"],
    cores: 6,
    cpuScore: 76,
    integratedGraphics: false,
    coolerIncluded: true,
    specs: ["6C/12T", "4.4 GHz Boost", "11th gen"],
  },
  {
    id: "cpu-12400f",
    name: "Core i5-12400F",
    brand: "Intel",
    category: "cpu",
    price: 27500,
    rating: 4.7,
    tdp: 65,
    socket: "LGA1700",
    memoryType: ["DDR4", "DDR5"],
    cores: 6,
    cpuScore: 96,
    integratedGraphics: false,
    coolerIncluded: true,
    specs: ["6C/12T", "4.4 GHz Boost", "12th gen"],
  },
];

const legacyMotherboards: MotherboardPart[] = [
  {
    id: "mb-a320m",
    name: "A320M-S2H",
    brand: "Gigabyte",
    category: "motherboard",
    price: 12000,
    rating: 4.0,
    tdp: 20,
    socket: "AM4",
    memoryType: "DDR4",
    formFactor: "Micro-ATX",
    memorySlots: 2,
    maxMemory: 64,
    specs: ["AM4", "DDR4", "Micro-ATX"],
  },
  {
    id: "mb-b450m",
    name: "B450M DS3H",
    brand: "Gigabyte",
    category: "motherboard",
    price: 18000,
    rating: 4.5,
    tdp: 22,
    socket: "AM4",
    memoryType: "DDR4",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    maxMemory: 128,
    specs: ["AM4", "DDR4", "Micro-ATX"],
  },
  {
    id: "mb-h110m",
    name: "H110M-K",
    brand: "ASUS",
    category: "motherboard",
    price: 8500,
    rating: 3.9,
    tdp: 18,
    socket: "LGA1151",
    memoryType: "DDR4",
    formFactor: "Micro-ATX",
    memorySlots: 2,
    maxMemory: 32,
    specs: ["LGA1151", "DDR4", "Micro-ATX"],
  },
  {
    id: "mb-b365m",
    name: "B365M PRO-VH",
    brand: "MSI",
    category: "motherboard",
    price: 12500,
    rating: 4.2,
    tdp: 20,
    socket: "LGA1151v2",
    memoryType: "DDR4",
    formFactor: "Micro-ATX",
    memorySlots: 2,
    maxMemory: 64,
    specs: ["LGA1151 v2", "DDR4", "Micro-ATX"],
  },
  {
    id: "mb-h510m",
    name: "H510M-H",
    brand: "Gigabyte",
    category: "motherboard",
    price: 14000,
    rating: 4.1,
    tdp: 20,
    socket: "LGA1200",
    memoryType: "DDR4",
    formFactor: "Micro-ATX",
    memorySlots: 2,
    maxMemory: 64,
    specs: ["LGA1200", "DDR4", "Micro-ATX"],
  },
  {
    id: "mb-b560m",
    name: "MAG B560M Bazooka",
    brand: "MSI",
    category: "motherboard",
    price: 20000,
    rating: 4.4,
    tdp: 25,
    socket: "LGA1200",
    memoryType: "DDR4",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    maxMemory: 128,
    specs: ["LGA1200", "DDR4", "Micro-ATX"],
  },
];

export const PARTS: Part[] = [
  ...cpus,
  ...legacyCpus,
  ...gpus,
  ...motherboards,
  ...legacyMotherboards,
  ...rams,
  ...storages,
  ...psus,
  ...coolers,
  ...cases,
];

export const PARTS_BY_ID: Record<string, Part> = Object.fromEntries(
  PARTS.map((p) => [p.id, p]),
);

export function partsFor(category: Category): Part[] {
  return PARTS.filter((p) => p.category === category);
}

export type Build = Partial<Record<Category, string>>;

/**
 * Price policy: every price is a NEW (boxed, warranty) retail price collected from
 * Algerian stores (Digitec, Campus Informatique, Alger/Oran retail) and is only
 * accepted when the listing is at most two months old.
 */
export const PRICE_META = {
  /** Last full market review (ISO date). */
  updatedAt: "2026-08-12",
  /** Oldest listing date accepted in this review. */
  validFrom: "2026-06-12",
  condition: "new" as const,
  currency: "DZD",
};

export function priceUpdatedLabel(lang: "ar" | "en" = "ar"): string {
  return lang === "ar"
    ? "أسعار قطع جديدة · محدّثة في 12/08/2026 (آخر شهرين)"
    : "New-part prices · reviewed 12 Aug 2026 (last 2 months)";
}

/** Algerian dinar formatting — prices reflect local retail (Alger/Oran) levels. */
export function formatPrice(value: number, lang: "ar" | "en" = "ar"): string {
  const n = Math.round(value).toLocaleString(lang === "ar" ? "ar-DZ" : "en-US");
  return lang === "ar" ? `${n} دج` : `${n} DZD`;
}
